language: node_js
node_js: 
  - 12
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
notifications:
  email: false
install:
  - npm install
script:
  - npm run travis
branches:
  only: master